[tool.ruff]
line-length = 120
# Rule descriptions: https://docs.astral.sh/ruff/rules/
# TODO enable more linter
#lint.select = ["I", "E", "B", "F", "W", "N", "C4", "C90", "ARG", "PL", "RUF", "UP"]

[tool.ruff.lint.per-file-ignores]
# Example ignore for all tests (Magic value used in comparison)
# We use magic values in tests
"tests/*" = ["PLR2004"]
# There is a loot to look at with this rule,
# not enforced yet
"*" = ["F401"]
